plugins {
    id 'com.android.application'
}

def commit = getGitCommitHash(file('.'))
def usePrebuiltNative = (project.findProperty("usePrebuiltNative") ?: "false").toString().toBoolean()

android {
    namespace 'ru.ytkab0bp.slicebeam'
    compileSdk 35

    defaultConfig {
        applicationId "com.codemastercody3d.orcaslicermobile"
        minSdk 21
        targetSdk 35
        versionCode 4
        versionName "0.4.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [fileProviderAuthority: "${applicationId}.provider"]

        if (!usePrebuiltNative) {
            externalNativeBuild {
                cmake {
                    arguments '-DANDROID_STL=c++_shared', '-DANDROID_PLATFORM=21',
                            '-DCMAKE_BUILD_TYPE=Release', // Disabling this results in drastically degradation of slicing times on debug builds
                            "-DSLIC3R_VERSION=\"${defaultConfig.versionName}\"",
                            "-DSLIC3R_BUILD_ID=\"${defaultConfig.versionCode}\""
                }
            }
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs += file('src/main/occt/jniLibs')
            if (usePrebuiltNative) {
                jniLibs.srcDirs += file('src/prebuiltNative/jniLibs')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "boolean", "IS_GOOGLE_PLAY", "false"
            buildConfigField "String", "COMMIT", "\"" + commit + "\""
            ndk {
                //noinspection ChromeOsAbiSupport
                abiFilters "arm64-v8a"
            }
        }
        debug {
            buildConfigField "boolean", "IS_GOOGLE_PLAY", "false"
            buildConfigField "String", "COMMIT", "\"" + commit + "\""
            ndk {
                debugSymbolLevel 'NONE'
                //noinspection ChromeOsAbiSupport
                abiFilters "arm64-v8a"
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    ndkVersion "28.2.13676358"

    if (!usePrebuiltNative) {
        externalNativeBuild {
            cmake {
                path file('CMakeLists.txt')
            }
        }
    }

    buildFeatures {
        buildConfig true
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "OrcaSlicerMobile_" + commit + ".apk"
        }
    }
}

static String getGitCommitHash(File dir) {
    try {
        return Runtime.getRuntime().exec("git rev-parse HEAD", null, dir).inputStream.readLines().get(0).substring(0, 10)
    } catch (Exception e){
        println("Unable to get git commit hash:")
        e.printStackTrace()
        return "non-git build"
    }
}

dependencies {
    implementation project(":eventbus")
    implementation project(":eventbus_api")
    annotationProcessor project(":eventbus_processor")
    implementation project(":sapil")

    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.github.instacart:truetime-android:4.0.0.alpha'
    implementation 'com.github.mrudultora:Colorpicker:1.2.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.loopj.android:android-async-http:1.4.11'
    implementation 'androidx.activity:activity:1.10.1'
}